name: ðŸš€ Deploy to SFTP

on:
  push:
    branches:
      - main
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  sftp-deploy:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    name: Upload via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install terser postcss postcss-nesting cssnano

      - name: Minify CSS and JS
        run: node minify.js

      - name: Check secrets presence
        run: |
          test -n "${{ secrets.SERVER }}" || (echo "SERVER is empty" && exit 1)
          test -n "${{ secrets.USERNAME }}" || (echo "USERNAME is empty" && exit 1)
          test -n "${{ secrets.PASSWORD }}" || (echo "PASSWORD is empty" && exit 1)
          test -n "${{ secrets.PORT }}" || (echo "PORT is empty" && exit 1)
          test -n "${{ secrets.THEME_PATH }}" || (echo "THEME_PATH is empty" && exit 1)

      - name: Deploy to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          remote_path: ${{ secrets.THEME_PATH }}
          delete_remote_files: false
          rsyncArgs: "--exclude=node_modules --exclude=package.json --exclude=package-lock.json"