name: ðŸš€ Deploy to SFTP

on:
  push:
    branches:
      - main
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  sftp-deploy:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    name: Upload via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: sftp
          port: ${{ secrets.PORT }}
          remote_path: ${{ secrets.THEME_PATH }}
          sftp_only: true
          delete: false
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/.DS_Store
